### ISSUE TITLE
Found a fatal error

### ISSUE THREAD

**Issue by dkragen** [julianxhokaxhiu/docker-powerdns#4]
Tried to use a modified version of your administrator-powerdns-recursor docker package and ran into some problems.  Went back to your setup and found the same fatal error.  Reviewing the logs of the container showed: "Fatal: Unable to connect to remote '/var/run/pdns_recursor.controlsocket': No such file or directory."  Went in separately via docker exec ... ls, and pdns_recursor.controlsocket is right where it should be...

**Comment by julianxhokaxhiu** [comment]
I'll try to replicate this on my side. Thanks for the feedback.

**Comment by julianxhokaxhiu** [comment]
May I ask if you're still facing the same issue @dkragen ?

**Comment by julianxhokaxhiu** [comment]
I've updated the whole stack for PowerDNS GUI. Now the latest build is running fine. Please use that one.
